spring.application.name=Library
spring.data.mongodb.uri=mongodb+srv://CVDSLab4:4A2PWrjXrWBMBgk9@cvdslab4.npvtm.mongodb.net/Library?retryWrites=true&w=majority
spring.profiles.active=test
spring.servlet.multipart.enabled=true
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=bibliosoftimages;AccountKey=FtasTB4RsMvusmlDqccHpoLZArvqdExiavX+EtLhVvAXl+vXLCFZZO3ZUxPJKs5sRwwWAyFfwNp2+ASt5DwC+A==;EndpointSuffix=core.windows.net
azure.storage.container-name=cbcods


