name: Branch Protection

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch origin
        run: |
          if [[ "${{ github.base_ref }}" == "master" && "${{ github.head_ref }}" != release/* ]]; then
            echo "ERROR: Only 'release/*' branches can be merged into 'main'."
            exit 1
          elif [[ "${{ github.base_ref }}" == release/* && "${{ github.head_ref }}" != "develop" ]]; then
            echo "ERROR: Only 'develop' branch can be merged into 'release/*'."
            exit 1
          elif [[ "${{ github.base_ref }}" == "develop" && "${{ github.head_ref }}" != feature/* ]]; then
            echo "ERROR: Only 'feature/*' branches can be merged into 'develop'."
            exit 1
          fi
